name: flirt_scan
description: FlirtScan Flutter app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Routing
  go_router: ^13.2.2
  
  # Icons
  flutter_svg: ^2.0.9
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Image Compression
  flutter_image_compress: ^2.1.0
  
  # Path Provider (for temporary file storage)
  path_provider: ^2.1.1
  
  # Firebase
  firebase_core: ^2.24.0
  cloud_functions: ^4.6.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Ads
  google_mobile_ads: ^5.1.0

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Internationalization
  generate: true
  
  # Assets
  assets:
    - assets/icons/
